// Generated by scripts/gen-component-types.cjs — do not edit.

import Direction from './Direction';
import Observed from './Observed';
import Position from './Position';
import RandomWalk from './RandomWalk';
import Size from './Size';
import Speed from './Speed';

export interface SimulatorComponents {
  Direction: typeof Direction;
  Observed: typeof Observed;
  Position: typeof Position;
  RandomWalk: typeof RandomWalk;
  Size: typeof Size;
  Speed: typeof Speed;
}

export { Direction, Observed, Position, RandomWalk, Size, Speed };
