// Generated by scripts/gen-component-types.cjs — do not edit.

import Direction from './Direction';
import Follow from './Follow';
import FollowTarget from './FollowTarget';
import FollowTightness from './FollowTightness';
import MaxSpeed from './MaxSpeed';
import Observed from './Observed';
import Position from './Position';
import RandomWalk from './RandomWalk';
import Size from './Size';
import Speed from './Speed';
import Wait from './Wait';
import Wander from './Wander';
import WanderPersistence from './WanderPersistence';

export interface SimulatorComponents {
  Direction: typeof Direction;
  Follow: typeof Follow;
  FollowTarget: typeof FollowTarget;
  FollowTightness: typeof FollowTightness;
  MaxSpeed: typeof MaxSpeed;
  Observed: typeof Observed;
  Position: typeof Position;
  RandomWalk: typeof RandomWalk;
  Size: typeof Size;
  Speed: typeof Speed;
  Wait: typeof Wait;
  Wander: typeof Wander;
  WanderPersistence: typeof WanderPersistence;
}

export { Direction, Follow, FollowTarget, FollowTightness, MaxSpeed, Observed, Position, RandomWalk, Size, Speed, Wait, Wander, WanderPersistence };
