// Generated by scripts/gen-component-types.cjs — do not edit.

import Collided from './Collided';
import Direction from './Direction';
import FloorTile from './FloorTile';
import Follow from './Follow';
import FollowTarget from './FollowTarget';
import FollowTightness from './FollowTightness';
import Grid from './Grid';
import GridResolution from './GridResolution';
import MaxSpeed from './MaxSpeed';
import Observed from './Observed';
import Obstacle from './Obstacle';
import ObstacleSize from './ObstacleSize';
import Position from './Position';
import PreviousPosition from './PreviousPosition';
import RandomWalk from './RandomWalk';
import Size from './Size';
import Speed from './Speed';
import VisualSize from './VisualSize';
import Wait from './Wait';
import Walkable from './Walkable';
import Wander from './Wander';
import WanderPersistence from './WanderPersistence';

export interface SimulatorComponents {
  Collided: typeof Collided;
  Direction: typeof Direction;
  FloorTile: typeof FloorTile;
  Follow: typeof Follow;
  FollowTarget: typeof FollowTarget;
  FollowTightness: typeof FollowTightness;
  Grid: typeof Grid;
  GridResolution: typeof GridResolution;
  MaxSpeed: typeof MaxSpeed;
  Observed: typeof Observed;
  Obstacle: typeof Obstacle;
  ObstacleSize: typeof ObstacleSize;
  Position: typeof Position;
  PreviousPosition: typeof PreviousPosition;
  RandomWalk: typeof RandomWalk;
  Size: typeof Size;
  Speed: typeof Speed;
  VisualSize: typeof VisualSize;
  Wait: typeof Wait;
  Walkable: typeof Walkable;
  Wander: typeof Wander;
  WanderPersistence: typeof WanderPersistence;
}

export { Collided, Direction, FloorTile, Follow, FollowTarget, FollowTightness, Grid, GridResolution, MaxSpeed, Observed, Obstacle, ObstacleSize, Position, PreviousPosition, RandomWalk, Size, Speed, VisualSize, Wait, Walkable, Wander, WanderPersistence };
