// Generated by scripts/gen-component-types.cjs — do not edit.

import Collided from './Collided';
import DefaultSpriteKey from './DefaultSpriteKey';
import Direction from './Direction';
import FloorTile from './FloorTile';
import Follow from './Follow';
import FollowTarget from './FollowTarget';
import FollowTightness from './FollowTightness';
import Food from './Food';
import Grid from './Grid';
import GridResolution from './GridResolution';
import Hero from './Hero';
import IsViewportFocus from './IsViewportFocus';
import MaxSpeed from './MaxSpeed';
import Observed from './Observed';
import Obstacle from './Obstacle';
import ObstacleSize from './ObstacleSize';
import Pointer from './Pointer';
import PointerTarget from './PointerTarget';
import PointerTile from './PointerTile';
import Position from './Position';
import PreviousPosition from './PreviousPosition';
import RandomWalk from './RandomWalk';
import Size from './Size';
import Speed from './Speed';
import VariantSpriteKey from './VariantSpriteKey';
import View from './View';
import VisualSize from './VisualSize';
import Wait from './Wait';
import Walkable from './Walkable';
import Wander from './Wander';
import WanderPersistence from './WanderPersistence';

export interface SimulatorComponents {
  Collided: typeof Collided;
  DefaultSpriteKey: typeof DefaultSpriteKey;
  Direction: typeof Direction;
  FloorTile: typeof FloorTile;
  Follow: typeof Follow;
  FollowTarget: typeof FollowTarget;
  FollowTightness: typeof FollowTightness;
  Food: typeof Food;
  Grid: typeof Grid;
  GridResolution: typeof GridResolution;
  Hero: typeof Hero;
  IsViewportFocus: typeof IsViewportFocus;
  MaxSpeed: typeof MaxSpeed;
  Observed: typeof Observed;
  Obstacle: typeof Obstacle;
  ObstacleSize: typeof ObstacleSize;
  Pointer: typeof Pointer;
  PointerTarget: typeof PointerTarget;
  PointerTile: typeof PointerTile;
  Position: typeof Position;
  PreviousPosition: typeof PreviousPosition;
  RandomWalk: typeof RandomWalk;
  Size: typeof Size;
  Speed: typeof Speed;
  VariantSpriteKey: typeof VariantSpriteKey;
  View: typeof View;
  VisualSize: typeof VisualSize;
  Wait: typeof Wait;
  Walkable: typeof Walkable;
  Wander: typeof Wander;
  WanderPersistence: typeof WanderPersistence;
}

export { Collided, DefaultSpriteKey, Direction, FloorTile, Follow, FollowTarget, FollowTightness, Food, Grid, GridResolution, Hero, IsViewportFocus, MaxSpeed, Observed, Obstacle, ObstacleSize, Pointer, PointerTarget, PointerTile, Position, PreviousPosition, RandomWalk, Size, Speed, VariantSpriteKey, View, VisualSize, Wait, Walkable, Wander, WanderPersistence };
