/**
 * ECS component definitions for the simulation.
 * Loaded via import.meta.glob; registration and public API from the same glob (no manual list).
 * Types are generated by scripts/gen-component-types.cjs from the same folder.
 * @packageDocumentation
 */

import { registerComponentForPipelineObserver } from '../observers';
import type { SimulatorComponents } from './components.generated';

export * from './components.generated';

const modules = import.meta.glob('./*.ts', { eager: true });

const SKIP_NAMES = new Set(['index', 'components.generated']);

function nameFromPath(path: string): string {
  const base = path.replace(/^\.\//, '').replace(/\.ts$/, '');
  return base;
}

for (const [path, mod] of Object.entries(modules)) {
  const name = nameFromPath(path);
  if (SKIP_NAMES.has(name)) continue;
  const comp = (mod as { default?: unknown }).default;
  if (comp) {
    registerComponentForPipelineObserver(comp as Record<string, unknown>);
  }
}

const components = Object.fromEntries(
  Object.entries(modules)
    .filter(([path]) => !SKIP_NAMES.has(nameFromPath(path)))
    .map(([path, mod]) => [
      nameFromPath(path),
      (mod as { default: unknown }).default,
    ])
) as unknown as SimulatorComponents;

export { components };
