import { createWorld, type World } from 'bitecs';
import {
  createObserverDeserializer,
  createSnapshotDeserializer,
  Observed,
  RENDER_COMPONENTS,
} from '@outside/simulator';

/**
 * Packet shape shared by renderers consuming simulator snapshots and deltas.
 */
export type RenderStreamPacket = {
  kind: 'snapshot' | 'delta';
  buffer: ArrayBuffer;
  tic: number;
};

/**
 * Local ECS state used by inspector renderer to replay simulator streams.
 */
export interface InspectorRenderWorld {
  world: World;
  observerDeserializer: ReturnType<typeof createObserverDeserializer>;
  snapshotDeserializer: ReturnType<typeof createSnapshotDeserializer>;
  lastTic: number;
}

/**
 * Creates an empty inspector render world configured for the simulator render schema.
 *
 * @returns A deserializer-backed world used by inspector rendering.
 */
export function createInspectorRenderWorld(): InspectorRenderWorld {
  const world = createWorld();
  return {
    world,
    observerDeserializer: createObserverDeserializer(world, Observed, [...RENDER_COMPONENTS]),
    snapshotDeserializer: createSnapshotDeserializer(world, [...RENDER_COMPONENTS]),
    lastTic: 0,
  };
}

/**
 * Applies one stream packet to the inspector render world.
 *
 * @param state - Inspector render world state.
 * @param packet - Snapshot or delta packet generated by the simulator.
 */
export function applyInspectorStream(state: InspectorRenderWorld, packet: RenderStreamPacket): void {
  if (packet.kind === 'snapshot') {
    state.snapshotDeserializer(packet.buffer);
  } else {
    state.observerDeserializer(packet.buffer);
  }
  state.lastTic = packet.tic;
}
